---
title: "Solar Adoption in New Jersey"
output: 
  flexdashboard::flex_dashboard:
    theme: default
    orientation: rows
    source_code: "https://github.com/psimran-singh/Data-Visualization-Final-Project"
    vertical_layout: scroll
runtime: shiny

---
```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
library(formattable)
library(DT)
library(lubridate)
library(xts)
library(dygraphs)
library(nivocal)
library(sf)
library(RColorBrewer)
library(leaflet)

setwd("~/GitHub/Data-Visualization-Final-Project/Data Files for Analysis")

## Section 1: Overall Landscape ##
# Load in all the data we need
load("Solar_All_County.Rda")
load("Solar_Res_County.Rda")
county_level_rates <- read_csv('County_Totals.csv')
county_level_sectors <- read_csv('County_Sectors.csv')
Solar_All_County <- st_as_sf(Solar_All_County) %>% st_transform(4326)
Solar_Res_County <- st_as_sf(Solar_Res_County) %>% st_transform(4326)


## Section 2: Overall Trends ## 
# Load in all the data we need
trend <- read_csv('Trend.csv')
trend_trans <- read_csv('Trend_Transposed.csv')
trend_yoy <- read_csv('Trend_Percents.csv')

```

Overall Landscape
=====================================

Current Landscape {.sidebar}
-----------------------------------------------------------------------

Pick a county to highlight below:

```{r}
selectInput("County", "County:", choices = distinct(county_level_rates, `County`))
```

Row
-----------------------------------------------------------------------

### Current Installed Solar Capacity

```{r}
renderValueBox({
  total_cap <- paste(prettyNum(county_level_rates[county_level_rates$County==input$County,4],big.mark=",",digits=0)," MW")
  valueBox(total_cap, 
           icon = "fa-sun")
})
```

### Current Installed Solar Projects

```{r}
renderValueBox({
  total_quant <- paste(prettyNum(county_level_rates[county_level_rates$County==input$County,2], big.mark=","))
  valueBox(total_quant,
           icon = "fa-solar-panel")
})
```

Row
-----------------------------------------------------------------------
### Total Capacity

```{r}
pal <- colorBin(palette = "Reds", domain = Solar_All_County$capacity_mw) # split colors from white to red into 9 even bins

leaflet() %>%
  addPolygons(data = Solar_All_County,
              label = ~County, # when you hover over the polygon, it will label the svi
              color = "gray", # the color of the border
              fillColor = ~pal(Solar_All_County$capacity_mw), # the colors inside the polygons
              weight = 1.0, # the thickness of the border lines
              opacity = 1.0, # the transparency of the border lines
              fillOpacity = 0.8) %>%
  addLegend(data = Solar_All_County, # the dataset
            "bottomright", # where to put the legend
            pal = pal, values = ~capacity_mw, # specify the color palette and the range of values 
            title = "Capacity (MW)", # legend title
            opacity = 1.0) # the transparency of the legend
```

### Total Quantity

```{r}
pal <- colorBin(palette = "Blues", domain = Solar_All_County$quantity) # split colors from white to red into 9 even bins

renderLeaflet(
  {solar_all_county0 <- county_level_sectors %>% filter(County != "Overall") %>%
    mutate(selected = ifelse(County == input$County, TRUE, FALSE)
    
  map1 <- leaflet() %>%
  addPolygons(data = Solar_All_County,
              label = ~County, # when you hover over the polygon, it will label the svi
              color = "gray", # the color of the border
              fillColor = ~pal(Solar_All_County$quantity), # the colors inside the polygons
              weight = 1.0, # the thickness of the border lines
              opacity = 1.0, # the transparency of the border lines
              fillOpacity = 0.8) %>%
  addLegend(data = Solar_All_County, # the dataset
            "bottomright", # where to put the legend
            pal = pal, values = ~quantity, # specify the color palette and the range of values 
            title = "# of Projects", # legend title
            opacity = 1.0) # the transparency of the legend

    map1}
)
```

Row {.tabset}
-----------------------------------------------------------------------

### Capacity by Sector

```{r}
renderPlotly(
  {county_level_sectors0 <- county_level_sectors %>% filter(County != "Overall") %>%
    mutate(selected = ifelse(County == input$County, TRUE, FALSE))
  
  colors <- county_level_sectors0 %>% select(County,selected) %>% 
    mutate(res_color = ifelse(selected == TRUE, "#6367CE", "#9FA3F2")) %>%
    mutate(nonres_color = ifelse(selected == TRUE, "#F1A73E", "#F7C57D")) %>%
    mutate(gs_color = ifelse(selected == TRUE, "#4DBA37", "#89EA76"))

fig <- plot_ly(county_level_sectors0, 
               x = county_level_sectors0$`County`, 
               y = (county_level_sectors0$`cap_res`/1000),
               type = "bar", 
               name = "Residential",
               marker = list(color = colors$res_color))  %>%
  add_trace(y = (county_level_sectors0$`cap_nonres`/1000),
            name = 'Non-Residential',
            marker = list(color = colors$nonres_color))  %>%
  add_trace(y = (county_level_sectors0$`cap_gs`/1000),
            name = 'Grid Supply',
            marker = list(color = colors$gs_color))  %>%
  layout(yaxis = list(title = "Capacity (MW)"), 
         xaxis = list(title = "Year",
                      tickangle = -45,
                      tickmode = 'linear', 
                      categoryorder = "total descending"),
         hovermode='x',
         barmode = "stack")
  fig}
)

```

### Quantity by Sector

```{r}
renderPlotly(
  {county_level_sectors0 <- county_level_sectors %>% filter(County != "Overall") %>%
    mutate(selected = ifelse(County == input$County, TRUE, FALSE))
  
  colors <- county_level_sectors0 %>% select(County,selected) %>% 
    mutate(res_color = ifelse(selected == TRUE, "#6367CE", "#9FA3F2")) %>%
    mutate(nonres_color = ifelse(selected == TRUE, "#F1A73E", "#F7C57D")) %>%
    mutate(gs_color = ifelse(selected == TRUE, "#4DBA37", "#89EA76"))

fig <- plot_ly(county_level_sectors0, 
               x = county_level_sectors0$`County`, 
               y = county_level_sectors0$`quant_res`,
               type = "bar", 
               name = "Residential",
               marker = list(color = colors$res_color))  %>%
  add_trace(y = county_level_sectors0$`quant_nonres`,
            name = 'Non-Residential',
            marker = list(color = colors$nonres_color))  %>%
  add_trace(y = county_level_sectors0$`quant_gs`,
            name = 'Grid Supply',
            marker = list(color = colors$gs_color))  %>%
  layout(yaxis = list(title = "quantacity (MW)"), 
         xaxis = list(title = "Year",
                      tickangle = -45,
                      tickmode = 'linear', 
                      categoryorder = "total descending"),
         hovermode='x',
         barmode = "stack")
  fig}
)

```


Overall Trends
=====================================

Row
-----------------------------------------------------------------------

### Year over Year Installed Capacity Growth (2020-2021)

```{r}
renderValueBox({
  cap_yoy <- paste(prettyNum(trend_yoy[22,9],big.mark=",",digits=2))
  valueBox(cap_yoy, 
     icon = "fa-sun")
})
```

### Year over Year Project Quantity Growth (2020-2021)

```{r}
renderValueBox({
  quant_yoy <- paste(prettyNum(trend_yoy[22,17],big.mark=",",digits=2))
  valueBox(quant_yoy,
           icon = "fa-solar-panel")
})
```


Row {.tabset}
-----------------------------------------------------------------------

### Cumulative Capacity Trend

```{r}
fig1 <- plot_ly(trend, x = ~Year, y = ~`Residential Capacity (Cumulative)`,
               type = 'scatter', mode = 'lines+markers', name = 'Residential') %>% 
  add_trace(y = ~`Non-Residential Capacity (Cumulative)`, name = 'Non-Residential') %>%
  add_trace(y = ~`Grid Supply Capacity (Cumulative)`, name = 'Grid Supply') %>%
  layout(yaxis = list(title = "Capacity (MW)"), 
         xaxis = list(title = "Year", tickangle = -45, tickmode = 'linear', limits=c(2000,2021)),
         hovermode='x')
fig1
```

### Yearly Capacity Growth Trend

```{r}
fig2 <- plot_ly(trend, x = ~Year, y = ~`Residential Capacity`,
               type = 'scatter', mode = 'lines+markers', name = 'Residential') %>%
  add_trace(y = ~`Non-Residential Capacity`, name = 'Non-Residential') %>%
  add_trace(y = ~`Grid Supply Capacity`, name = 'Grid Supply') %>%
  layout(yaxis = list(title = "Capacity (MW)"),
         xaxis = list(title = "Year", tickangle = -45, tickmode = 'linear'),
         hovermode='x')
fig2
```

### Cumulative Quantity Trend

```{r}
fig3 <- plot_ly(trend, x = ~Year, y = ~`Residential Quantity (Cumulative)`,
               type = 'scatter', mode = 'lines+markers', name = 'Residential') %>%
  add_trace(y = ~`Non-Residential Quantity (Cumulative)`, name = 'Non-Residential') %>%
  add_trace(y = ~`Grid Supply Quantity (Cumulative)`, name = 'Grid Supply') %>%
  layout(yaxis = list(title = "Quantity"),
         xaxis = list(title = "Year", tickangle = -45, tickmode = 'linear'),
         hovermode='x')
fig3
```

### Yearly Quantity Growth Trend

```{r}
fig4 <- plot_ly(trend, x = ~Year, y = ~`Residential Quantity`,
               type = 'scatter', mode = 'lines+markers', name = 'Residential') %>%
  add_trace(y = ~`Non-Residential Quantity`, name = 'Non-Residential') %>%
  add_trace(y = ~`Grid Supply Quantity`, name = 'Grid Supply') %>%
  layout(yaxis = list(title = "Quantity"),
         xaxis = list(title = "Year", tickangle = -45, tickmode = 'linear'),
         hovermode='x')
fig4
```

Row {.tabset}
-----------------------------------------------------------------------

### Overall

```{r}
DT::renderDataTable({
  DT::datatable(trend_trans,
                class = 'compact nowrap cell-border stripe',
                extensions = c('Responsive','Scroller','Buttons'), 
                escape = FALSE, 
                rownames = FALSE,
                options = list(bPaginate = FALSE,
                               ordering=FALSE,
                               autoWidth = TRUE,
                               scrollX=TRUE,
                               searching = FALSE,
                               buttons = c('colvis', 'excel')))
})
```

### Residential

```{r}
DT::renderDataTable({
  DT::datatable(trend_trans,
                class = 'cell-border stripe',
                extensions = 'Responsive', 
                escape = FALSE, 
                rownames = FALSE, 
                options = list(bPaginate = FALSE,
                               ordering=FALSE,
                               autoWidth = TRUE,
                               scrollX=TRUE,
  columnDefs = list(list(width = '200px', targets = "_all"),
                    list(className = 'dt-center', targets = "_all"))))
})
```


### Non-Residential

```{r}
DT::renderDataTable({
  DT::datatable(trend_trans,
                class = 'cell-border stripe',
                extensions = 'Responsive', 
                escape = FALSE, 
                rownames = FALSE, 
                options = list(bPaginate = FALSE,
                               ordering=FALSE,
                               autoWidth = TRUE,
                               scrollX=TRUE,
  columnDefs = list(list(width = '200px', targets = "_all"),
                    list(className = 'dt-center', targets = "_all"))))
})
```

### Grid Supply

```{r}
DT::renderDataTable({
  DT::datatable(trend_trans,
                class = 'cell-border stripe',
                extensions = 'Responsive', 
                escape = FALSE, 
                rownames = FALSE, 
                options = list(bPaginate = FALSE,
                               ordering=FALSE,
                               autoWidth = TRUE,
                               scrollX=TRUE,
  columnDefs = list(list(width = '200px', targets = "_all"),
                    list(className = 'dt-center', targets = "_all"))))
})
```
